import ajax from "./ajax";
//1、根据经纬度获取位置详情](#1根据经纬度获取位置详情)
const reqAddress = (geohash) => ajax(`/position/${geohash}`)
//2、获取食品分类列表](#2获取食品分类列表)
const reqFoodTypes = () => ajax(`/index_category`)
//3、根据经纬度获取商铺列表](#3根据经纬度获取商铺列表)
const reqShops = (longitude, latitude) => ajax(`/shops`, {longitude, latitude})
//4、根据经纬度和关键字搜索商铺列表](#4根据经纬度和关键字搜索商铺列表)
const reqSearchShops = (geohash, keyword) => ajax(`/search_shops`, {geohash, keyword})
//5、获取一次性验证码](#5获取一次性验证码)
const reqAuthCode = () => ajax(`/captcha`)
//6、用户名密码登陆](#6用户名密码登陆)
const reqPasswordLogin = (name, pwd, captcha) => ajax(`/login_pwd`, {name, pwd, captcha}, 'POST')
//7、发送短信验证码](#7发送短信验证码)
const reqSMSVerification = (phone) => ajax(`/sendcode`, {phone})
//8、手机号验证码登陆](#8手机号验证码登陆)
const reqSPhoneVerification = (phone, code) => ajax(`/login_sms`, {phone, code}, 'POST')
//9、根据会话获取用户信息](#9根据会话获取用户信息)
const reqUserInfo = () => ajax(`/userinfo`)
//10、用户登出](#10用户登出)
const reqLogout = () => ajax(`/logout`)
